### ISSUE TITLE
Auto-exercise of ITM options

### ISSUE THREAD

**Issue by zareth-san** [sirenmarkets/core#13]
Currently if an ITM option is not exercised before expiration it would expire worthless even though it has significant value. In TradFi all platforms auto-exercise options.

Possible solutions:

- We run an oracle that goes over all expiring contracts and exercises them using a special oracleExercise function. The oracle doesn't have to supply the price, the price can be taken on-chain. (pros: no action from users, cons: requires us to run an oracle)

- Allow both buyer and seller to trigger the claim function that uses current on-chain underlying price to perform an exercise and exchange tokens into payment tokens automatically (pros: no oracle is needed, cons: requires user action)

The auto-exerciser oracle could use a uniswap flash loan to pay for exercising. i.e.:
    
1. Borrow exercise amount in USDC from uniswap
2. Exercise, receive WBTC
3. Repay Uniswap using WBTC
4. Send the rest to bToken holder

**Comment by ferdousbhai** [comment]
auto-exerciser oracle is the way to go. 👍
