### ISSUE TITLE
Allow rewards to be claimed on behalf of other addresses

### ISSUE THREAD

**Issue by calebsheridan** [sirenmarkets/core#28]
# Background

The current staking rewards may only be claimed by an address that directly interacts with StakingRewards.sol by calling `getReward()`. The rewards are always sent to `msg.sender`. This issue adds logic for rewards to be claimed on behalf of another account. The advantage is one of flexibility for the future, e.g. to more easily enable keepers for yield aggregators.

# Scope

* New function in [StakeRewards.sol](https://github.com/sirenmarkets/core/blob/master/contracts/staking/StakingRewards.sol#L106): `getRewardFor(address)`

# Functionality

`getRewardFor(address account)` uses the same functionality as `getReward()`, replacing `msg.sender` with `account`

Optionally, `getReward()` could call `getRewardFor(msg.sender)` to avoid code duplication.

**Comment by thenameisdarryl** [comment]
+1 I will encounter the same issue.

**Comment by Ozzchain** [comment]
@randhydra @seafi any clarity here? this was pushed over two weeks ago.

**Comment by wbnns** [comment]
@calebsheridan @thenameisdarryl @Ozzchain 

Hello, just wanted to keep you all posted that this is still under review and is on our radar.

**Comment by seafi** [comment]
StakeRewards.sol won't be used for rewards distribution. Instead it'll be a different contract that allows anyone to claim rewards for any address by providing an off-chain signed message. That should address your use case.
